uploadPath:
  D:\dev_lab\07.myBatis\dev-mybatis\src\main\webapp\pds\
server:
  port: 8000
  tomcat:    
    additional-tld-skip-patterns: "*.jar"
logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521/orcl11
      username: scott
      password: tiger
      driver-class-name: oracle.jdbc.OracleDriver
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: oraPool
